### ISSUE TITLE
Add support for variables in path

### ISSUE THREAD

**Issue by karanrajpal14** [utkarsh9891/PackageSync#6]
Hey,
Is there any chance you can add support for Windows System variables in the path so that I don't have to configure my Dropbox path every time?
I specifically want to use `%USERPROFILE% `
Here's a list of them and what they do:
[Windows Environment Variables](http://www.askvg.com/list-of-environment-variables-in-windows-xp-vista-and-7/)

**Comment by utkarsh9891** [comment]
You should have to configure the DropBox path only once. The path is then stored in the user settings of sublime text. Can you please elaborate on the issue you are facing?

**Comment by utkarsh9891** [comment]
@karanrajpal14, please update on this issue. Adding support for Windows Systems Variables does not seem like a required or useful addition right now. Probably some details into the requirements you have for this might help me understand the use case better.

**Comment by karanrajpal14** [comment]
Hey @utkarsh9891 I'm really sorry for the late reply.
Let me explain my issue to you. 

I have two devices at home and my Sublime Text is present on Dropbox. I usually use it from there as it allows me to access my work from anywhere and it keeps everything consolidated. 

Now, when I run PackageSync on my PC whose username is `Karan Rajpal`, the Dropbox path there is Karan Rajpal `C:\Users\Karan Rajpal\Dropbox` and it syncs just fine. 

But, when I make some changes on my laptop, whose username is `Karan`, I can't run PackageSync because, naturally the path `C:\Users\Karan Rajpal\Dropbox` is not found since it is `C:\Users\Karan\Dropbox` in this case and the sync fails.

It would be easier to just set the Dropbox path to `%USERPROFILE%\Dropbox` and it would just work across both my devices. Makes sense?

**Comment by utkarsh9891** [comment]
Sorry for the late response @karanrajpal14.

Given that you use Sublime Text from within your Dropbox folder itself, I do not see why you would need to use PackageSync at all. If the SublimeText installation folder is the Dropbox folder itself, the package listing & your user settings for other Sublime Packages would already be syncing to your devices via Dropbox. That is something that PackageSync tries to achieve for normal installations in the user's application directories.

If I understand correctly, logging in into Dropbox on any fresh device would effectively result in downloading the entire sublime installation on that device. That in turn would also download/sync your packages & settings on that device. I do not see any use of PackageSync's online syncing feature here.

Having said that, I would advise you against using the sync client's folder as SublimeText's installation folder. You could always keep your project directories inside the client's folders. But installing Sublime Text there as well removes your flexibility to keep the Sublime installation different across different machines.

Let me know if this answers your query. In case you want to reach me offline, please feel free to ping me at utkarsh9891@gmail.com.

**Comment by utkarsh9891** [comment]
@karanrajpal14, please let me know if your problem is solved.

**Comment by utkarsh9891** [comment]
@karanrajpal14: Marking this as resolved due to no reply form your end for quite some time now.
