### ISSUE TITLE
create folder in google drive

### ISSUE THREAD

**Issue by navotera** [utkarsh9891/PackageSync#7]
i already create folder in my gdrive with **anyone with link can edit** and paste the shareable link to the user config but this plugin show that my folder is invalid. 

please give any suggestion. here my folder : https://drive.google.com/drive/folders/0BzirfvUIrXAURm5fN05wWUhZQ3M?usp=sharing

**Comment by utkarsh9891** [comment]
Can you please share the logs from the console when Sublime Text starts?

**Comment by navotera** [comment]
**here the log**
error: Invalid path provided for online_sync_folder in PackageSync settings. Online syncing has been turned off. Please correct and retry.
 https://drive.google.com/drive/folders/0BzirfvUIrXAURm5fN05wWUhZQ3M
reloading /C/Users/hendra/AppData/Roaming/Sublime Text 3/Packages/User/PackageSync.sublime-settings
reloading settings Packages/User/PackageSync.sublime-settings

**my folder is here :** 
https://drive.google.com/drive/folders/0BzirfvUIrXAURm5fN05wWUhZQ3M

thanks

**Comment by utkarsh9891** [comment]
It seems like you have copied the http url to the google driver folder.
Instead, please copy the path of the local folder from your disk.

**Comment by navotera** [comment]
so u tell me this plugin is sync to local folder then the online sync is done by google drive itself ?

**Comment by utkarsh9891** [comment]
What this plugin does is it copies files form your local google drive folder (where you google drive files are synced) to the sublime install folder. When anything changes in you local sublime installation, the changes are copied to the files in the google drive local folder. That gets synced to other devices via google drive application. In those devices, sublime again copies the files back to local sublime installation folder from the google drive folders.
Therefore, the path to be mentioned for online syncing is the path to the local folder where google drive syncs it's contents.

**Comment by navotera** [comment]
ok, i think u should noted that statement in the read me or manual page. thanks
